#!/usr/bin/env node
/**
 * prefetch-check.js
 *
 * Dev script: verifies every asset the offline CV/STT/PWA path
 * depends on actually resolves on disk before you trust an airplane-mode
 * test. Run after `npm run fetch-assets` and before a cold-launch rehearsal.
 */

import { existsSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PUBLIC = path.join(ROOT, "public");

const REQUIRED = [
  // MediaPipe Tasks Vision wasm (self-hosted)
  "wasm/mediapipe/vision_wasm_internal.js",
  "wasm/mediapipe/vision_wasm_internal.wasm",
  "wasm/mediapipe/vision_wasm_nosimd_internal.js",
  "wasm/mediapipe/vision_wasm_nosimd_internal.wasm",
  // Object detection model
  "models/efficientdet_lite0.tflite",
  // Tesseract OCR core + worker (self-hosted)
  "wasm/tesseract/worker.min.js",
  "wasm/tesseract/tesseract-core-lstm.wasm",
  "wasm/tesseract/tesseract-core-lstm.wasm.js",
  "wasm/tesseract/tesseract-core-simd-lstm.wasm",
  "wasm/tesseract/tesseract-core-simd-lstm.wasm.js",
  "models/tessdata/eng.traineddata.gz",
  // Vosk STT model
  "models/vosk/vosk-model-small-en-us-0.15.tar.gz",
  // Compiled UI (generated by @iwsdk/vite-plugin-uikitml on dev/build — run
  // `npm run dev` or `npm run build` at least once before this check if
  // these are missing)
  "ui/welcome.json",
  "ui/hud.json",
];

let missing = 0;
let totalBytes = 0;

console.log("Sight2Sheet prefetch check\n");
for (const rel of REQUIRED) {
  const full = path.join(PUBLIC, rel);
  if (!existsSync(full)) {
    console.error(`  MISSING  ${rel}`);
    missing += 1;
    continue;
  }
  const { size } = statSync(full);
  totalBytes += size;
  console.log(`  ok       ${rel}  (${(size / 1024 / 1024).toFixed(2)} MB)`);
}

console.log(
  `\nTotal: ${(totalBytes / 1024 / 1024).toFixed(1)} MB across ${REQUIRED.length - missing}/${REQUIRED.length} required assets.`,
);

if (missing > 0) {
  console.error(
    `\n${missing} asset(s) missing. Run "npm run fetch-assets" to fetch them.`,
  );
  process.exit(1);
}

console.log(
  "\nAll assets present. If the PWA precache list (vite.config.ts) matches" +
    " this set, an airplane-mode cold launch should have everything it needs.",
);
